### ISSUE TITLE
enable Fast Forward in time

### ISSUE THREAD

**Issue by aslesani** [openshs/openshs#3]
Hi.
I have a question. When I start the simulator and walk-in home, how can I enable the fast forward in time as shown in the demo? When I press the 'space', I just can select the current activity.
In addition, how can I edit the list of available activities?

**Comment by nashamri** [comment]
@aslesani Hello there,
When pressing `space` the dialog that shows up allows you to choose the activity and the duration of the activity. You can enter the duration of the currently selected activity by typing the number of seconds, like in the screenshot:
![screenshot_20180723_000144](https://user-images.githubusercontent.com/1207107/43050097-060c307a-8e0c-11e8-92b7-c4391f992c8a.png)
The picture shows that `sleep` is the currently selected activity and the duration is 30 seconds. If you click `Ok` that will record `sleep` in the dataset and skip in time 30 seconds forward.

As for adding more activities, you can simply add a new button here (don't forget to position the button):
https://github.com/openshs/openshs/blob/master/app/blender/ui.py#L33
and hook up the signal here:
https://github.com/openshs/openshs/blob/master/app/blender/ui.py#L55

For example, to add a new activity called `study` you can do something like this:
```python
        self.sleep_btn      = bgui.FrameButton(self.frame, text='sleep', size=[0.1, 0.05], pos=[0.90, 0.95])
        self.eat_btn        = bgui.FrameButton(self.frame, text='eat', size=[0.1, 0.05], pos=[0.90, 0.90])
        self.personal_btn   = bgui.FrameButton(self.frame, text='personal', size=[0.1, 0.05], pos=[0.90, 0.85])
        self.work_btn       = bgui.FrameButton(self.frame, text='work', size=[0.1, 0.05], pos=[0.90, 0.80])
        self.leisure_btn    = bgui.FrameButton(self.frame, text='leisure', size=[0.1, 0.05], pos=[0.90, 0.75])
        self.anomaly_btn    = bgui.FrameButton(self.frame, text='anomaly', size=[0.1, 0.05], pos=[0.90, 0.70])
        self.other_btn      = bgui.FrameButton(self.frame, text='other', size=[0.1, 0.05], pos=[0.90, 0.65])
        self.study_btn      = bgui.FrameButton(self.frame, text='study', size=[0.1, 0.05], pos=[0.90, 0.60])

        self.ok_btn = bgui.FrameButton(self.frame, text='Ok',
                size=[0.3, 0.1], pos=[0, 0.2], options=bgui.BGUI_CENTERX)

        self.cancel_btn = bgui.FrameButton(self.frame, text='Cancel',
                size=[0.3, 0.1], pos=[0, 0.1], options=bgui.BGUI_CENTERX)

        self.activity_duration_input = bgui.TextInput(self.frame, prefix="Activity Duration: ", text='0',
                pt_size=30, pos=[0, 0.4], size=[0.3, 0.05], options=bgui.BGUI_CENTERX)
        self.activity_duration_input.visible = False
        self.activity_duration = 0

        # signals
        self.ok_btn.on_click = self.ok_btn_click
        self.cancel_btn.on_click = self.cancel_btn_click
        self.sleep_btn.on_click = self.set_activity_click
        self.eat_btn.on_click = self.set_activity_click
        self.personal_btn.on_click = self.set_activity_click
        self.work_btn.on_click = self.set_activity_click
        self.leisure_btn.on_click = self.set_activity_click
        self.anomaly_btn.on_click = self.set_activity_click
        self.other_btn.on_click = self.set_activity_click
        self.study_btn.on_click = self.set_activity_click

```

Notice line numebr 8 where we create the button, and line number 31 where we connect the signal to the button.

Hope this helps, 
~ Nasser

**Comment by aslesani** [comment]
Thanks a lot.
I do not know why, but most of the times after pressing the space button, the activity duration text box does not appear. I think maybe it is because of setting it invisible.
`        self.activity_duration_input.visible = False
`
Am I right?

**Comment by nashamri** [comment]
Did you start the simulation via the `openshs` command or did you open the `.blend` files directly?
Try running this for example, from the `app` directory:
`./openshs start -c morning`
or
`python openshs start -c morning`

**Comment by aslesani** [comment]
I start the simulation by the command in python console. I modified the code and set all of the activity_duration_input visibility to True and now it works fine. 
Thanks.

**Comment by nashamri** [comment]
Okay that's good :+1: have fun :smile:

**Comment by aslesani** [comment]
Is it important to click some special points, when we want to open a door? Sometimes the door does not open. what is the reason? I think just some area of the door handle is clickable. right?

**Comment by nashamri** [comment]
Yeah that was intentional, you need to click on the handle. Also, you need
to be close from the door to be able to open it, because there's a
proximity sensor there. All of that was just to make it a bit realistic.

**Comment by aslesani** [comment]
Yes, that is very good. But sometimes clicking the handle does not change the status of the door. I do not know the reason.

**Comment by nashamri** [comment]
Umm, it could be a collision issue, because the avatar's body is kind of a 3D rectangler shape, and the head of the avatar is moving freely with the mouse, and the camera is locked to the head. So, I think sometimes, when you come at a certain angle to the door, the proximity sensor won't hit or detect the avatar's body. This is my guess, I'm not 100% sure :smile:
